exclude: ^(tests/.*)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.3.0"
    hooks:
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-docstring-first
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.6.4"
    hooks:
      - id: ruff
        args: [--extend-select, I, --fix, --line-length=120]
      - id: ruff-format
        args: [--line-length=120]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.1"
    hooks:
      - id: prettier
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.11.2"
    hooks:
      - id: mypy
        exclude: ^tests/
        args:
          [
            --disallow-untyped-defs,
            --disallow-incomplete-defs,
            --disallow-untyped-calls,
            --ignore-missing-imports,
          ]
  - repo: https://github.com/codespell-project/codespell
    rev: "v2.2.6"
    hooks:
      - id: codespell
