name: "Test package creation and running"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "poetry config virtualenvs.create false" >> ~/.bashrc
          source ~/.bashrc
          poetry --version

      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Run tests for isv loss
        run: |
          poetry run genovisio-report --annot tests/annotation_test_loss.json.gz --isv tests/isv_loss.json --marcnv tests/marcnv.json --hybrid tests/hybrid.json --out_html tests/test_output_loss.html --out_csv tests/test_output_loss.csv --workflow_version 0.1.2

      - name: Compare outputs html
        run: |
          diff tests/test_output_loss.html tests/expected_output_loss.html

      - name: Compare outputs csv
        run: |
          diff tests/test_output_loss.csv tests/expected_output_loss.csv

      - name: Run tests for isv gain
        run: |
          poetry run genovisio-report --annot tests/annotation_test_gain.json.gz --isv tests/isv_gain.json --marcnv tests/marcnv.json --hybrid tests/hybrid.json --out_html tests/test_output_gain.html --out_csv tests/test_output_gain.csv --workflow_version 0.1.2

      - name: Compare outputs html
        run: |
          diff tests/test_output_gain.html tests/expected_output_gain.html

      - name: Compare outputs csv
        run: |
          diff tests/test_output_gain.csv tests/expected_output_gain.csv
